name: CI

on:
  push:
    branches:
      - main

jobs: 
  call-build-in-libs:
    uses: ./.github/workflows/build.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}